modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/noeppi-noeppi/bongo/issues"
license="Apache-2.0"

[[mods]]
modId="bongo"
version="${file.jarVersion}"
displayName="Bongo-unofficial"
displayURL="https://github.com/Rinkore/Bongo"
updateJSONURL="https://assets.melanx.de/updates/bongo.json"
authors="rinkore"
description='''
It's a bingo mod forked by https://github.com/noeppi-noeppi/Bongo/tree/1.18.
'''

[[dependencies.bongo]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="skyblockbuilder"
    mandatory=false
    versionRange="[1.18.1-3.0.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minemention"
    mandatory=false
    versionRange="[1.18.2-1.3.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="jei"
    mandatory=false
    versionRange="[9.4.3.123,)"
    ordering="NONE"
    side="BOTH"
